Star schema
oracle/quicksql pull request #20
Opened 2023-10-31 17:11 UTC by vadim-tropashko

2023-10-31 18:37 UTC, mig8447 commented on doc/user/quick-sql-grammar.md
> +  - [Star/Snowflake schema relationship direction indicators](#starsnowflake-schema-relationship-direction-indicators)
indentation should be 4 spaces

2023-10-31 18:37 UTC, mig8447 commented on doc/user/quick-sql-grammar.md
> -      - [apex](#apex)
indentation should be 4 spaces

2023-10-31 18:37 UTC, mig8447 commented on doc/user/quick-sql-grammar.md
> +
This space is unnecessary

2023-10-31 18:39 UTC, mig8447 commented on doc/user/quick-sql-grammar.md
> +![Sales-Product-Customer Example](../../test/star/sales_product_customers.qsql)
This should not be an image but a bare link

```suggestion
[Sales-Product-Customer Example](../../test/star/sales_product_customers.qsql)
```

2023-10-31 18:44 UTC, mig8447 requested changes

2023-10-31 18:44 UTC, mig8447 commented on doc/user/quick-sql-grammar.md
> +In star (and snowflake) database model tables are organized into a hierarchy where the table at the top (fact) is in many-to-one relationship to children (dimension tables). Consequently, each dimens
- [ ] Use an 80 characters rule, instead of a very long line
- [ ] Change QSQL for Quick SQL (Two words)

2023-10-31 18:44 UTC, mig8447 commented on doc/user/quick-sql-grammar.md
> +The more-than symbol `>` hints the many-to-one relationship between the table cardinalities. The opposite -- one-to-many relationship -- is denoted by the `<` prefix, which is default, and is usually
Fix text to an 80 char rule

2023-10-31 18:44 UTC, mig8447 commented on doc/user/quick-sql-grammar.md
> +The database defined via QuickSQL is populated with the data generated by ![chancejs](https://github.com/chancejs/chancejs). If QSQL code has been generated from json document, then the document is k
- [ ] Change this to an 80 character rule
- [ ] Change QuickSQL and QSQL to Quick SQL

2023-10-31 18:44 UTC, mig8447 commented on doc/user/quick-sql-grammar.md
> +![Syntax Railroad Diagram](./railroad.xhtml)
This should not be an image but a bare link

```suggestion
[Syntax Railroad Diagram](./railroad.xhtml)
```

2023-10-31 18:44 UTC, mig8447 commented on doc/user/railroad.xhtml
> +<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml">
Can you paste a screenshot of the diagram on the PR?

2023-10-31 21:47 UTC, vadim-tropashko commented
<img width="688" alt="Screenshot 2023-10-31 at 2 46 36 PM" src="https://github.com/oracle/quicksql/assets/145372301/ec9b91a8-26c5-4a76-8f62-6a2d82f590df">

2023-11-07 16:56 UTC, mig8447 approved these changes

2023-11-07 16:57 UTC, merged